# Allowed variables:
#
# {{ date }}          The current date
# {{ time }}          The current time
prompt: "{{ date }} {{ time }} # "

commands:
  # Command structure:
  #
  # commandname:
  #   class: (string)
  #   args: (int)
  #
  # A corresponding class should be created in the commands directory
  # named "commandCommandname". Use the php template file for a starting
  # point.
  commands:
    class: \phpsh\Commands\CommandCommands
  exit:
    class: \phpsh\Commands\CommandExit
  help:
    class: \phpsh\Commands\CommandHelp
  shutdown:
    class: \phpsh\Commands\CommandShutdown
  sleep:
    class: \phpsh\Commands\CommandSleep
    args: 1
  startup:
    class: \phpsh\Commands\CommandStartup

on_startup: "startup"

on_shutdown: "shutdown"